
language: python

cache: pip

env:
  - 'PYLINT_ENABLE=1'

python:
  - "2.7"
  - "3.6"

matrix:
  allow_failures:
    - python: "3.6"

install:
  - pip install -r test-requirements.txt

script:
  - bash tests/travis-runner.sh
